name: Print Secrets and Variables

on:
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print ORG_SECRET
        env:
          ORG_SECRET: ${{ secrets.ORG_SECRET }}
        run: echo "ORG_SECRET=$ORG_SECRET"

      - name: Print ORG_VARIABLE
        run: echo "ORG_VARIABLE=${{ vars.ORG_VARIABLE }}"

      - name: Print REPO_SECRET
        env:
          REPO_SECRET: ${{ secrets.REPO_SECRET }}
        run: echo "REPO_SECRET=$REPO_SECRET"

      - name: Print REPO_VARIABLE
        run: echo "REPO_VARIABLE=${{ vars.REPO_VARIABLE }}"
